default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: mangio
  password: samara_code
  host: localhost

development:
  <<: *default
  database: mangio_development

test:
  <<: *default
  database: mangio_test

production:
  <<: *default
  database: mangio_production
  username: mangio
  password: <%= ENV['DATABASE_PASSWORD'] %>
